

---
- hosts: 192.168.112.190
  tasks: 
  - name: Stop docker container
    shell: "docker-compose down"
    args:
      chdir: ~/test_ansible
  - name: Remove old directory
    shell: "rm -rf ~/test_ansible"
  


